"""
Guest room strip on conference-venues-with-accommodation.html. 23 Sep 2026.

One card per Australian venue visit that has a photograph in its Accommodation
section, linking to the record under /venue-visits/. Written between
<!-- rooms:start --> and <!-- rooms:end --> inside the "In short" band.
Everything outside the markers is untouched, so it is safe to re-run.

Nothing here is typed by hand:
  - the venue list, name, city and meta line come from the "Firsthand" bands
    that scripts/sync-venue-visit-bands.py already writes on the destination
    pages, so a card here can never disagree with the city page or the record
  - the image and its alt come from the first photograph in the record's own
    Accommodation section; a record with none is skipped and named in the output
  - width and height are read off the real file with PIL

Australian only because the page it sits on lists Australian venues. Ordered by
published room count, largest first; a venue with no count sorts last.

Runs automatically at the end of sync-venue-visit-bands.py. On its own:

    python3 scripts/sync-rooms-strip.py            # write
    python3 scripts/sync-rooms-strip.py --check    # drift, exit 1
"""
import glob, html as H, io, os, re, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, 'conference-venues-with-accommodation.html')
START, END = '<!-- rooms:start', '<!-- rooms:end -->'
IMG_TAG = re.compile(r'''<img\b(?:[^>"']|"[^"]*"|'[^']*')*>''')

CITY = {'gold-coast': 'Gold Coast', 'sunshine-coast': 'Sunshine Coast',
        'hunter-valley': 'Hunter Valley', 'blue-mountains': 'Blue Mountains',
        'byron-bay': 'Byron Bay', 'yarra-valley': 'Yarra Valley',
        'mornington-peninsula': 'Mornington Peninsula'}
# A card's city label. Bunker Bay sits on the Perth page but is not in Perth.
PLACE = {'pullman-bunker-bay': 'Margaret River region'}


def attr(tag, name):
    m = re.search(r'\s%s="([^"]*)"' % name, tag)
    return m.group(1) if m else ''


def rooms_of(meta):
    m = re.search(r'([\d,]+)\s+(?:rooms|villas|suites)', H.unescape(meta))
    return int(m.group(1).replace(',', '')) if m else -1


def venues():
    out, seen = [], set()
    for f in sorted(glob.glob(os.path.join(ROOT, 'venue-finder-*.html'))):
        slugc = os.path.basename(f)[13:-5]
        city = CITY.get(slugc, slugc.replace('-', ' ').title())
        page = io.open(f, encoding='utf-8').read()
        band = re.search(r'<!-- vwalk:start.*?<!-- vwalk:end -->', page, re.S)
        if not band:
            continue
        for href, name, meta in re.findall(
                r'<li class="vwalk__card"><a href="([^"]+)">.*?<b>(.*?)</b>\s*'
                r'<span class="vwalk__meta">(.*?)</span>', band.group(0), re.S):
            slug = href.strip('/').split('/')[-1]
            if slug in seen:
                continue
            seen.add(slug)
            out.append(dict(slug=slug, href=href, name=name, meta=meta,
                            city=PLACE.get(slug, city)))
    return out


def guest_room(v):
    rec = os.path.join(ROOT, 'venue-visits', v['slug'], 'index.html')
    if not os.path.isfile(rec):
        return None
    h = io.open(rec, encoding='utf-8').read()
    sec = re.search(r'<h2[^>]*>[^<]*ccommodation[^<]*</h2>(.*?)</section>', h, re.S)
    if not sec:
        return None
    for t in IMG_TAG.findall(sec.group(1)):
        src = attr(t, 'src')
        if 'venue-visits/' not in src:
            continue
        src = re.sub(r'^(\.\./)+', '', src.split('?')[0])
        path = os.path.join(ROOT, src)
        if not os.path.isfile(path):
            continue
        alt = attr(t, 'alt')
        plain = H.unescape(alt).strip()
        if plain == H.unescape(v['name']).strip() or not plain:
            alt = '%s, guest room' % v['name']
        w, hgt = Image.open(path).size
        return dict(src=src, alt=alt, w=w, h=hgt)
    return None


def card(v, g):
    return (
        '    <li class="rstrip__card"><a href="%s">\n'
        '      <span class="rstrip__img"><img src="%s" alt="%s" loading="lazy" decoding="async" width="%d" height="%d"></span>\n'
        '      <span class="rstrip__body"><b>%s</b><span class="rstrip__city">%s</span>'
        '<span class="rstrip__meta">%s</span></span></a></li>\n'
    ) % (v['href'], g['src'], g['alt'], g['w'], g['h'], v['name'], v['city'], v['meta'])


def block(cards):
    if not cards:
        return START + ' GENERATED by scripts/sync-rooms-strip.py, do not edit by hand -->\n' + END
    n = len(cards)
    words = {2: 'Two', 3: 'Three', 4: 'Four', 5: 'Five', 6: 'Six', 7: 'Seven',
             8: 'Eight', 9: 'Nine', 10: 'Ten', 11: 'Eleven', 12: 'Twelve'}
    lead_n = words.get(n, str(n))
    return (
        START + ' GENERATED by scripts/sync-rooms-strip.py, do not edit by hand -->\n'
        '<div class="rstrip-wrap" id="rooms-we-have-seen">\n'
        '  <div class="section-head"><span class="eyebrow">Firsthand</span>\n'
        '    <h2 class="h2">The rooms upstairs, in venues we have walked.</h2>\n'
        '    <p class="lead">%s residential venues we have been through ourselves, guest rooms included. '
        'Each one opens our record of the visit: the published capacities, the date we were there, '
        'and an honest word on what it suits.</p></div>\n'
        '  <ul class="rstrip" tabindex="0" role="list" aria-label="Guest rooms in venues we have walked">\n'
        '%s'
        '  </ul>\n'
        '  <div class="btn-row mt-2"><a class="btn btn--ghost" href="venue-visits/">See every venue we have walked '
        '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7" '
        'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div>\n'
        '</div>\n' + END
    ) % (lead_n, ''.join(cards))


def main():
    check = '--check' in sys.argv
    cards, skipped = [], []
    for v in sorted(venues(), key=lambda v: -rooms_of(v['meta'])):
        if 'no accommodation' in v['meta'].lower():
            continue
        g = guest_room(v)
        if not g:
            skipped.append(v['name'])
            continue
        cards.append(card(v, g))
    page = io.open(PAGE, encoding='utf-8').read()
    new = block(cards)
    if START in page:
        out = re.sub(re.escape(START) + r'.*?' + re.escape(END), lambda m: new, page, flags=re.S)
    else:
        # First run: inside the "In short" band, straight after the answer box.
        anchor = re.search(r'(<div class="vidx-answer answer-solo">.*?</div>\n)', page, re.S)
        if not anchor:
            sys.exit('anchor not found in %s' % PAGE)
        out = page[:anchor.end()] + new + '\n' + page[anchor.end():]
    print('rooms strip: %d card(s)' % len(cards))
    if skipped:
        print('  no Accommodation photo in the record, so not shown: %s' % ', '.join(skipped))
    if out == page:
        print('  unchanged')
        return
    if check:
        print('DRIFT: run python3 scripts/sync-rooms-strip.py')
        sys.exit(1)
    io.open(PAGE, 'w', encoding='utf-8').write(out)
    print('  written')


if __name__ == '__main__':
    main()
