#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Push every published venue visit onto the destination page for its city.

    python3 scripts/sync-venue-visit-bands.py --check     report drift, exit 1
    python3 scripts/sync-venue-visit-bands.py --dry-run   show what would change
    python3 scripts/sync-venue-visit-bands.py             write it

WHY THIS EXISTS
    A venue visit record used to reach its destination page by hand. On
    8 September 2026 there were fourteen published records and five cards
    across four destination pages, so nine visits were invisible to anyone
    who arrived on a city page, and venue-finder-gold-coast.html had no band
    at all while The Star Gold Coast sat published in the hub. The work was
    real and the pages were not showing it.

WHERE THE FACTS COME FROM
    Nothing is retyped here. The script reads the two files that already
    define a venue visit and never executes either of them, because importing
    them rebuilds live pages as a side effect:

      _venue-visits-source/build_venue.py   VENUES: name, kind, city,
      _venue-visits-source/venues_more.py   MORE:   cityfile, metaline
      _venue-visits-source/build_hub.py     RECORDS: card image, alt, card line

    The Westin Brisbane is the one exception. It was built before the VENUES
    structure existed and build_westin.py hardcodes its page, so its headline
    facts sit in LEGACY below, read off its own record.

    Add a venue to those files the way you always have and it appears on the
    right destination page the next time this runs. There is no fifteenth
    place to update.

WHAT IT WRITES
    One band per destination page, between vwalk:start and vwalk:end markers,
    ordered by the largest capacity the venue publishes. Everything outside
    the markers is untouched. Re-running changes nothing unless the venue data
    changed, so it is safe in a loop and safe to put in front of a publish.

    Existing bands are adopted in place on the first run. A city that has no
    band yet gets one immediately before its snapshot band, which is where the
    other four pages carry it.
"""
import ast, io, os, re, shutil, sys, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, '_venue-visits-source')
BACKUP = os.path.join(ROOT, '_backup-pre-walkbands-08sep')

# The Westin predates the VENUES structure. Everything here is read off its own
# published record, and it is the only venue that needs an entry.
LEGACY = {
  'the-westin-brisbane': dict(
    slug='the-westin-brisbane', name='The Westin Brisbane', kind='Hotel',
    city='Brisbane', cityfile='venue-finder-brisbane.html',
    metaline=['400 theatre', '280 banquet', '298 rooms', 'Brisbane CBD']),
}

# Card sentences already approved and live on a destination page. They are
# softer than the hub's, which is deliberate, so they win over the hub line.
DEST_LINE = {
  'crown-towers-sydney': 'One ballroom at 390 theatre and two rooms that hold forty. A luxury hotel for a senior audience rather than a full conference.',
  'hotel-indigo-melbourne-little-collins': '179 rooms over ten floors in the CBD with one boardroom for twelve. We keep it in mind for delegate rooms rather than for the conference itself.',
  'pullman-quay-grand-sydney': 'An all suite hotel on East Circular Quay with three bookable spaces, the largest seating 70. Lovely for a board dinner or an executive program, rather than a conference.',
}

EYE = ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" '
       'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
       '<path d="M2 12s3.6-6 10-6 10 6 10 6-3.6 6-10 6-10-6-10-6z"/>'
       '<circle cx="12" cy="12" r="2.6"/></svg>')
ARROW = ('<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" '
         'stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
         '<path d="M5 12h14M13 6l6 6-6 6"/></svg>')

ACCOM = re.compile(r'\b(rooms|villas|suites?|apartments|accommodation)\b', re.I)
SETUP = re.compile(r'([\d,]+)\s*(theatre|banquet|cocktail|gala|boardroom|classroom|cabaret)', re.I)
SQM   = re.compile(r'([\d,]+)\s*sqm', re.I)
START = '<!-- vwalk:start GENERATED by scripts/sync-venue-visit-bands.py, do not edit by hand -->'
END   = '<!-- vwalk:end -->'


def dict_calls(path, required):
    """dict(...) literals out of a source file, read with ast, never executed."""
    tree = ast.parse(io.open(path, encoding='utf-8').read())
    out = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                and node.func.id == 'dict'):
            continue
        d = {}
        for kw in node.keywords:
            try:
                d[kw.arg] = ast.literal_eval(kw.value)
            except Exception:
                pass                      # a field built from a name, not needed here
        if all(k in d for k in required):
            out.append(d)
    return out


def load():
    facts = dict(LEGACY)
    for f in ('build_venue.py', 'venues_more.py'):
        for d in dict_calls(os.path.join(SRC, f), ('slug', 'cityfile', 'metaline')):
            facts[d['slug']] = d
    cards = {}
    for d in dict_calls(os.path.join(SRC, 'build_hub.py'), ('slug', 'img', 'line')):
        cards[d['slug']] = d

    venues = []
    for slug, f in facts.items():
        c = cards.get(slug)
        if not c:
            print('  skipped %s: in the venue data but not in the hub RECORDS' % slug)
            continue
        if not os.path.isdir(os.path.join(ROOT, 'venue-visits', slug)):
            print('  skipped %s: no published record at venue-visits/%s/' % (slug, slug))
            continue
        venues.append(dict(
            slug=slug, name=f['name'], city=f['city'], cityfile=f['cityfile'],
            meta=metaline(f), line=DEST_LINE.get(slug, c['line']),
            img=re.sub(r'^\.\./', '', c['img']),
            alt=c.get('alt') or '%s, %s' % (f['name'], f['city']),
            rank=rank(f)))
    return venues


def metaline(f):
    """Kind, the venue's headline capacity, then its accommodation if it has any.

    Reproduces the five cards that were already live, from the same metaline
    the record page uses, so the card and the record can never disagree."""
    ml = list(f['metaline'])
    cap = next((x for x in ml if SETUP.search(x)), None)
    accom = next((x for x in ml if ACCOM.search(x) and x != cap), None)
    picked = [x for x in (cap, accom) if x]
    for x in ml:                     # a venue that publishes neither, e.g. IHG
        if len(picked) >= 2:
            break
        if x not in picked and x != ml[-1]:
            picked.append(x)
    return ' &middot; '.join([f['kind']] + picked)


def rank(f):
    """Sort key. The venue's own headline capacity, then its largest published area.

    Headline rather than largest, so the order on the page matches the numbers
    printed on the cards: a venue showing 170 theatre never sits under one
    showing 140. A venue that publishes neither sorts to the bottom of its city
    rather than being given a number nobody published."""
    m0 = SETUP.search(' '.join(f['metaline']))
    seat = int(m0.group(1).replace(',', '')) if m0 else 0
    area = max([int(m.group(1).replace(',', '')) for m in SQM.finditer(' '.join(f['metaline']))] or [0])
    return (-seat, -area, f['name'])


def card(v, dims):
    w, h = dims
    return (
'    <li class="vwalk__card"><a href="venue-visits/%(slug)s/">\n'
'      <span class="vwalk__img"><img src="%(img)s" alt="%(alt)s" loading="lazy" decoding="async" width="%(w)d" height="%(h)d"></span>\n'
'      <span class="vwalk__body">\n'
'        <b>%(name)s</b>\n'
'        <span class="vwalk__meta">%(meta)s</span>\n'
'        <span class="vwalk__line">%(line)s</span>\n'
'        <span class="vwalk__seen">%(eye)sInspected by CVBS</span>\n'
'      </span></a></li>' % dict(v, w=w, h=h, eye=EYE))


def band(city, vs, dims):
    cards = '\n'.join(card(v, dims[v['slug']]) for v in vs)
    return (
'%(start)s\n'
'<section class="s-white pad" id="%(key)s-walked"><div class="wrap">\n'
'  <div class="section-head"><span class="eyebrow">Firsthand</span>\n'
'    <h2 class="h2">%(city)s venues we have walked through.</h2>\n'
'    <p class="lead">A few of the %(city)s venues we&rsquo;ve been through ourselves. For each one you&rsquo;ll find the venue&rsquo;s own published capacities, the date we were there, and an honest word about what it suits and what it doesn&rsquo;t.</p></div>\n'
'  <ul class="vwalk">\n'
'%(cards)s\n'
'  </ul>\n'
'  <div class="btn-row mt-2"><a class="btn btn--ghost" href="venue-visits/">See every venue we have walked %(arrow)s</a></div>\n'
'</div></section>\n'
'%(end)s' % dict(start=START, end=END, key=city.lower().replace(' ', '-'),
                 city=city, cards=cards, arrow=ARROW))


def dimensions(v):
    p = os.path.join(ROOT, v['img'])
    if not os.path.isfile(p):
        sys.exit('missing card image for %s: %s' % (v['slug'], v['img']))
    from PIL import Image
    with Image.open(p) as im:
        return im.size


def splice(html, city, new):
    """Replace the band between the markers, adopt an unmarked one, or insert."""
    key = city.lower().replace(' ', '-')
    if START in html and END in html:
        a = html.index(START)
        b = html.index(END) + len(END)
        return html[:a] + new + html[b:], 'updated'
    m = re.search(r'<section class="s-\w+ pad" id="%s-walked">' % re.escape(key), html)
    if m:
        end = html.index('\n</div></section>', m.start()) + len('\n</div></section>')
        return html[:m.start()] + new + html[end:], 'adopted'
    anchor = re.search(r'\n<section class="s-\w+ pad" id="%s-(snapshot|venues|at-a-glance)"' % re.escape(key), html)
    if not anchor:
        anchor = re.search(r'\n<section class="cta-band pad">', html)
    if not anchor:
        sys.exit('no place to put the %s band' % city)
    return html[:anchor.start() + 1] + new + '\n' + html[anchor.start() + 1:], 'inserted'


def main():
    check = '--check' in sys.argv
    dry = '--dry-run' in sys.argv or check
    venues = load()
    pages = {}
    for v in venues:
        pages.setdefault((v['city'], v['cityfile']), []).append(v)

    dims = {v['slug']: dimensions(v) for v in venues}
    drift = []
    for (city, cityfile), vs in sorted(pages.items()):
        vs.sort(key=lambda v: v['rank'])
        path = os.path.join(ROOT, cityfile)
        if not os.path.isfile(path):
            print('  %-32s NO SUCH PAGE, %d visit(s) have nowhere to go: %s'
                  % (cityfile, len(vs), ', '.join(v['name'] for v in vs)))
            continue
        html = io.open(path, encoding='utf-8').read()
        out, how = splice(html, city, band(city, vs, dims))
        same = out == html
        print('  %-34s %-9s %d card(s)%s' % (cityfile, how, len(vs), '' if same else '  CHANGED'))
        if same:
            continue
        drift.append(cityfile)
        if dry:
            continue
        if not os.path.isdir(BACKUP):
            os.makedirs(BACKUP)
        if not os.path.isfile(os.path.join(BACKUP, os.path.basename(path))):
            shutil.copy2(path, os.path.join(BACKUP, os.path.basename(path)))
        io.open(path, 'w', encoding='utf-8').write(out)

    print('%d venue visit(s) across %d destination page(s)' % (len(venues), len(pages)))

    # The safety net. A published record that carries no facts would simply not
    # be written, and the card would disappear off the destination page without
    # anything failing. That is how The Westin nearly went missing.
    published = set(os.path.basename(os.path.dirname(p)) for p in
                    glob.glob(os.path.join(ROOT, 'venue-visits', '*', 'index.html')))
    missing = sorted(published - set(v['slug'] for v in venues))
    if missing:
        print('PUBLISHED BUT NOT ON ANY DESTINATION PAGE: %s' % ', '.join(missing))
        print('add the venue to _venue-visits-source, or to LEGACY in this script')
        if check:
            sys.exit(1)

    if check and drift:
        print('DRIFT: %s' % ', '.join(drift))
        print('run: python3 scripts/sync-venue-visit-bands.py')
        sys.exit(1)


if __name__ == '__main__':
    main()
